version: "3.7"
services:
  case-study:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: case-study
    ports:
      - "8080:8080"
    volumes:
      - ../logs:/apps/docker/logs
    depends_on:
      - redis
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
networks:
  default:
    name: case-study
