version: "3.7"
services:
  case-study:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: case-study
    ports:
      - "8080:8080"
    volumes:
      - ../logs:/apps/docker/logs
    depends_on:
      - redis
  redis:
    image: redis:5.0.7
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus/
      - ./prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
networks:
  default:
    name: case-study
